name: Automate Attendance Tracking

on:
  schedule:
    - cron: "20 19 * * *"  # Runs at 7:20 PM UTC

  workflow_dispatch:  # Allows manual execution

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Previous attendance.json (if exists)
        continue-on-error: true  # ✅ Prevents failure if artifact is missing
        uses: actions/download-artifact@v4
        with:
          name: attendance-data
          path: .

      - name: Ensure attendance.json exists
        run: |
          if [ ! -f attendance.json ]; then
            echo "{}" > attendance.json  # ✅ Creates an empty JSON file if not found
            echo "attendance.json was missing. Created a new one."
          else
            echo "attendance.json found."
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'  # Enables caching for pip packages

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Attendance Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python tracker.py

      - name: Upload Updated attendance.json
        uses: actions/upload-artifact@v4
        with:
          name: attendance-data
          path: attendance.json

      - name: Upload notification.csv
        if: success()  # ✅ Upload only if script runs successfully
        uses: actions/upload-artifact@v4
        with:
          name: attendance-notification
          path: notification.csv
