name: Automate Attendance Tracking

on:
  schedule:
    - cron: "38 19 * * *"  # Runs at 7:20 PM UTC (Adjust as needed)

  workflow_dispatch:  # Allows manual execution

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Previous attendance.json
        uses: actions/download-artifact@v4
        with:
          name: attendance-data
          path: .

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'  # Enables caching for pip packages

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Attendance Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python tracker.py

      - name: Upload Updated attendance.json
        uses: actions/upload-artifact@v4
        with:
          name: attendance-data
          path: attendance.json

      - name: Upload notification.csv
        uses: actions/upload-artifact@v4
        with:
          name: attendance-notification
          path: notification.csv
